### ISSUE TITLE
Update `theme.toml`

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#304]
I notice a few choice lines in the [current](https://github.com/The-Balance-FFXIV/glam/blob/5031a03ff7364243c49f5841c74eb725aac156ea/theme.toml) theme.toml:

```toml
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
homepage = "http://example.com/"
min_version = "0.41.0"
```

Those (at least) are likely in need of review and updating.
