### ISSUE TITLE
guide meta seems broken on some pages:

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/glam#70]
For example, see here:

![image](https://user-images.githubusercontent.com/83298827/140621584-77abc018-d421-4c9e-93e5-c3d03463bb72.png)

Here's the frontmatter for that page in particular

```yaml
---
title: DRG Leveling Guide
authors:
  - Balance DRG Staff
patch: "5.58"
lastmod: 2021-10-29T02:47:11.508Z
changelog:
  - date: 2021-10-29T02:48:36.195Z
    message: Created page
---
```

My operating theory is that something bad is broken in one of the following areas:

* setting some of the tab-specific css for the front-page role slider made it unusable in other areas
* the frontmatter's author section having a space in the name makes it very unhappy
* I don't know, please help me
